//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scheduler.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Global {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Global() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Scheduler.Domain.Resources.Global", typeof(Global).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Occurs {0}, Schedule will be used on {1} at {2} starting on {3}.
        /// </summary>
        internal static string Description_SchedulerNextExecution {
            get {
                return ResourceManager.GetString("Description_SchedulerNextExecution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Occurs the {0} day every {1} months every {2} {3} between {4} and {5} starting on {6}.
        /// </summary>
        internal static string Description_SchedulerNextExecutionMonthlyDay {
            get {
                return ResourceManager.GetString("Description_SchedulerNextExecutionMonthlyDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Occurs the {0} {1} of every {2} months every {3} {4} between {5} and {6} starting on {7}.
        /// </summary>
        internal static string Description_SchedulerNextExecutionMonthlyEvery {
            get {
                return ResourceManager.GetString("Description_SchedulerNextExecutionMonthlyEvery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The fields {0} and {1} cannot be activated at same time, you must select only one to operate. Please check the configuration and try again..
        /// </summary>
        internal static string Error_DailyInputBoth {
            get {
                return ResourceManager.GetString("Error_DailyInputBoth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The field {0} cannot be greater than {1}. Please check the configuration and try again..
        /// </summary>
        internal static string Error_DateTimeGreater {
            get {
                return ResourceManager.GetString("Error_DateTimeGreater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The field {0} is empty and is neccesary to operate with the selected configuration. Please check it and try again..
        /// </summary>
        internal static string Error_EmptyInput {
            get {
                return ResourceManager.GetString("Error_EmptyInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The fields {0} and {1} are empty, you must select only one to operate. Please check the configuration and try again..
        /// </summary>
        internal static string Error_EmptyInputBoth {
            get {
                return ResourceManager.GetString("Error_EmptyInputBoth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The {0} field has an incorrect value, check the configuration and try again..
        /// </summary>
        internal static string Error_IncorrectValue {
            get {
                return ResourceManager.GetString("Error_IncorrectValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There is a problem calculating the Next Execution Time, please try again later..
        /// </summary>
        internal static string Error_OutputDateTimeNull {
            get {
                return ResourceManager.GetString("Error_OutputDateTimeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The Scheduler can not be null. Ensure that the info is correct..
        /// </summary>
        internal static string Error_SchedulerNull {
            get {
                return ResourceManager.GetString("Error_SchedulerNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Once.
        /// </summary>
        internal static string TypeConfiguration_Once {
            get {
                return ResourceManager.GetString("TypeConfiguration_Once", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recurring.
        /// </summary>
        internal static string TypeConfiguration_Recurring {
            get {
                return ResourceManager.GetString("TypeConfiguration_Recurring", resourceCulture);
            }
        }
    }
}
